### ISSUE TITLE
Square title buttons

### ISSUE THREAD

**Issue by mibeon** [darkomarko42/Marwaita-manjaro#2]
Hello Friend!

I have three questions, to make this theme be the best theme I ever used!

1: Window controls (min, max, close): Could give some short advice, how can I make the window title buttons not rounded, but kinda square with some little border radius.
2: Man window background color: I would set the background color of the apps to clear white. Could give here a tip?
3: Selection color/background: I would also want to change the selection color. I looked into the theme files, but didn't found the related place in my quick overview. Maybe you are lucky and could give also some info about this.

This theme is one of the best, of not the best out there.
So, at this state I want to say thanks for your effort!

Thank you vary much for your response!

**Comment by darkomarko42** [comment]
you can change the roundness of the windows control on the line in the file called "shared-settings.css":

"/* Headerbar buttons */

headerbar button.titlebutton:not(.suggested-action):not(.destructive-action),
.titlebar button.titlebutton:not(.suggested-action):not(.destructive-action),
windowcontrols > button:not(.titlebutton):not(.suggested-action):not(.destructive-action):not(.text-button),
.titlebar windowcontrols > button:not(.titlebutton):not(.suggested-action):not(.destructive-action):not(.text-button),
headerbar windowcontrols > button:not(.titlebutton):not(.suggested-action):not(.destructive-action):not(.text-button)
{border-radius: 9999px - HERE -; background-color: transparent; box-shadow: none; border: 1px solid transparent;}"

change the main view background color on the file "light.css": 

"@define-color view_bg_color mix(@window_bg_color,white,0.5);" replace to "@define-color view_bg_color white;"

the accent/selection color is on the first line of the file "shared-settings": @define-color accent_color #0f6ee3;

**Comment by mibeon** [comment]
Thank you, friend, for your friendly answer! 🙏
